name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: check docker status
        run: |
              systemctl status docker

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create kind cluster
        run: kind create cluster --config=multinodes.yaml

      - name: Check Cluster Info
        run: |
          kubectl cluster-info
      
      - name: Deploy Ingress controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl create serviceaccount build-robot
          kubectl get serviceaccounts
          kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
          kubectl apply -f deploy_ingress.yaml
      
      - name: Run the results of foo and bar
        run: |
         docker ps -a
         kubectl get service -n ingress-nginx
         curl localhost/bar
