name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: check docker status
        run: |
              systemctl status docker

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create kind cluster
        run: |
          kind create cluster  --config=multinodes.yaml
          curl https://docs.projectcalico.org/manifests/calico.yaml -O
          kubectl apply -f calico.yaml
          kubectl describe node kind-worker 

      - name: Check Cluster Info
        run: |
          kubectl cluster-info --context kind-kind
          kubectl get nodes
      
