name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: check docker status
        run: |
              systemctl status docker

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create kind cluster
        run: |
          kind delete cluster
          kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml
          kind create cluster  --config=multinodes.yaml
          kubectl describe node kind-worker 

      - name: Check Cluster Info
        run: |
          kubectl cluster-info --context kind-kind
          kubectl get nodes
      
