name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
              sudo apt install docker.io
              sudo apt install golang-go
              go install sigs.k8s.io/kind@v0.17.0
              systemctl start docker

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create kind cluster
        uses: kind create cluster --config=multinodes.yaml

      - name: Test
        run: |
          kubectl cluster-info
      
      - name: Run a one-line script
        run: echo Hello, world!
